# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r

r:
  - release
  - devel

r_build_args: --resave-data=best

dist: trusty

cache: packages

warnings_are_errors: false

sudo: false
